/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xxxxx_xxxxxxx_streams_NativeSign__ */

#ifndef _Included_com_xxxxx_xxxxxxx_streams_NativeSign__
#define _Included_com_xxxxx_xxxxxxx_streams_NativeSign__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xxxxx_xxxxxxx_streams_NativeSign__
 * Method:    signMm64
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xxxxx_xxxxxxx_streams_NativeSign_00024_signMm64
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
